var search={
  "<label properties>": "http://skosplus.net/skos-light/label-properties",
  "<scheme properties>": "http://skosplus.net/skos-light/scheme-properties",
  "<semantic relation properties>": "http://skosplus.net/skos-light/semantic-relation-properties",
  "Concept": "http://skosplus.net/skos-light/nonns_Concept.html",
  "Labeling System Label": "http://skosplus.net/skos-light/nonns_Label.html",
  "Labeling System Vocabulary": "http://skosplus.net/skos-light/nonns_Vocabulary.html",
  "SKOSlight Label": "http://skosplus.net/skos-light/Label",
  "SKOSlight Ontology": "http://skosplus.net/skos-light/",
  "SKOSlight Vocabulary": "http://skosplus.net/skos-light/Vocabulary",
  "Structural Concept": "http://skosplus.net/skos-light/StructualConcept",
  "broader": "http://skosplus.net/skos-light/nonns_broader.html",
  "has related label": "http://skosplus.net/skos-light/hasRelatedLabel",
  "has sub label": "http://skosplus.net/skos-light/hasSubLabel",
  "has super label": "http://skosplus.net/skos-light/hasSuperLabel",
  "has type": "http://skosplus.net/skos-light/hasType",
  "narrower": "http://skosplus.net/skos-light/nonns_narrower.html",
  "related": "http://skosplus.net/skos-light/nonns_related.html",
  "structural property": "http://skosplus.net/skos-light/structuralProperty"
}