name: Ontology Documentation CI

on: [push]

jobs:
     
  ontdocII:
        uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
        name: Ontdoc II      
        with:  
              version: v018 
              rdffilepath: skos-light.ttl
              docpath: docs/
              prefixns: http://skosplus.net/skos-light/
              prefixnsshort: skosplus
              indexpages: true
              metadatatable: true
              createcollections: false
              createnonNSPages: true
              createVOWL: true
              preferredlang: en
              ghpages: true
